### ISSUE TITLE
Support for custom job interpreter

### ISSUE THREAD

**Issue by bdehamer** [CircleCI-Public/circleci-runner-docker#18]
This feature request isn't specific to the docker packaging of the launch-agent but I wasn't sure where to make this request as it doesn't appear the `circleci-launch-agent` source is public.

We have a bunch of use cases where we want to run some task-specific jobs in our internal network where we can grant them access to sensitive resources. The CircleCI runner allows us to do this, but we want to take it even further and put some constraints in place to control precisely what job steps a developer can execute when sending jobs to one of our runners. For example we want to allow a job to use a private key to generate a signature for an artifact . . . but want to put some controls in place to ensure that key can't be exfiltrated.

We've cobbled together a solution which works, but would love to see first-class support in the launch agent for overriding the job interpreter. Currently, we're leveraging the fact that the task-agent always invokes `/bin/bash` to execute the jobs steps. We've replaced Bash in our runner image with a custom application which looks at the job description and decides whether or not it will allow it to be executed.

We're aware of the "command_prefix" config option, but it appears that the specified command is invoked by the launch-agent BEFORE the task-agent is started and lacks access to the list of job steps to be executed.

**Comment by kmannuz** [comment]
I'm working through the above as well ^ 

There's also this which you should upvote @bdehamer https://circleci.canny.io/runner-feature-requests/p/ability-to-restrict-runner-usage

**Comment by christian-stephen** [comment]
Hey, thanks for bringing this feature request to our attention.

For your specific use case on using a private key to generate a signature for an artifact, I believe [restricted contexts](https://circleci.com/docs/2.0/contexts/#restricting-a-context) might fit your need there.

If the Canny idea that @kmannuz has linked doesn't fit your general need for Runner access control, we do encourage you to open a [Canny post](https://circleci.canny.io/) for a custom job interpreter.
